### ISSUE TITLE
Wrong HTTP Method for Toy control

### ISSUE THREAD

**Issue by Er1807** [markviews/VRChatVibratorController#18]
Wrong HTTP Method for sending commands to Lovense Connect. Should be GET instead of POST.
I couldnt test it with the android version as it refused to connect. But the PC version could recieve commands again
```
//send data to toy
function send(url) {
    url = url.replace("https://", "")
    var htt = "https://";
    if (document.getElementById("http").checked) {
        htt = "http://";
        url = url.replace(".lovense.club:34568", ":34567")
        url = url.replaceAll("-", ".")
    }
    
	//console.log("Sending: " + url)
	if (stack.length != 0) {
		stack.push(url)
		return;
	}
	http.open("POST", htt + url) -> http.open("GET", htt + url)
	http.send()
}
```

As the LAN API isn't really supported by Lovense anymore if I have time I'm gonna work on adding support for the Standart API

**Comment by Er1807** [comment]
Added the API.
https://github.com/Er1807/VRChatVibratorController/blob/main/Sever/WEB-Server/public/script.js

For local testing it accesses a websocket on localhost. needs to be changed back to the original value.

**Comment by markviews** [comment]
updated, thank you.
