### ISSUE TITLE
Values for Vibrate Command should be between 0 and 20

### ISSUE THREAD

**Issue by Er1807** [markviews/VRChatVibratorController#21]
Currently all parts of the programm seem to set the limit between 0 and 10.

**Comment by markviews** [comment]
I think this should fix it. I assume double speed would be double as loud so.. I'll conform it works tomorrow.
https://github.com/markviews/VRChatVibratorController/releases/tag/1.3.3

**Comment by Er1807** [comment]
Doesnt work. The Server / Web recieves still values between 0 and 10. 
![image](https://user-images.githubusercontent.com/20169013/121770162-fc4e6c00-cb67-11eb-96f6-1fe3c3467fd7.png)

I also fucked up with the js code. 
instead of sendeing the speed to the lovense API it always sends 0. Fixed version below and in my repo
```
switch(args[0]) {
	case "speed":
		//controllerClient setting toy speed
		var id = args[1]
		var speed = args[2]
		var toy = myToys.get(id)
		var edgeVibrator = ""
		if (args.length == 4) {
			edgeVibrator = args[3]
		}
		lovense.sendCommand(`Vibrate${edgeVibrator}`,{v:speed, t:id});
		document.getElementById(id + "speed" + edgeVibrator).value = speed
	break;
	case "air":
		var id = args[1]
		var speed = args[2]
		var toy = myToys.get(id)
		lovense.sendCommand("AirAuto",{v:speed, t:id});
		document.getElementById(id + "air").value = speed
	break;
	case "rotate":
		var id = args[1]
		var toy = myToys.get(id)
		lovense.sendCommand("RotateChange",{t:id});
```

**Comment by markviews** [comment]
ok I updated the website script, thank you.
I'll try to fix the radial menu now.

Wow i'm impressed that you reverse engineered my server! Here's the code i'm running if you're interested in seeing it.
https://github.com/markviews/VRChatVibratorController/blob/a14bfcde04b966b921294aafde5473055ace7f6b/Server/vibe.js#L1-L177
