### ISSUE TITLE
Control Client disconnects

### ISSUE THREAD

**Issue by ZephyrPi** [markviews/VRChatVibratorController#26]
Control Client always disconnects immediately after updating the value in action menu. Unable to reconnect until restarting VRChat and reentering the code.

**Comment by Er1807** [comment]
Didnt have this issue but also expierienced that the connection sometime dropped. Think a automatic reconnect might be good. Maybe even with saving the last used token.

**Comment by markviews** [comment]
#27  should fix this. thank you Er1807!

**Comment by CyanTabby** [comment]
This might be an unusual request but would you mind deleting this issue? Thanks in advance
