### ISSUE TITLE
Webpage does not connect to Toy

### ISSUE THREAD

**Issue by M1zuke** [markviews/VRChatVibratorController#30]
Hey, i tried this mod out. But sadly i couldn't get the website to work for me. 
My Smarphone is reachable on the IP 192.168.178.22 in my local network. and i wrote this ip into the website. eiter with dashes or with dots. didnt make a difference.

My Smartphone is an Apple Iphone. and i allowed the lovense control app to be able to look through network. but it still does not resolve the webpage request.

is there something I'm missing.

![image](https://user-images.githubusercontent.com/59958391/135230011-5a802da8-5a61-4807-8c5d-11646e8e0d11.png)

**Comment by M1zuke** [comment]
Okay Update: I get back an empty list of toys. even tho my toy is connected in the lovense connect app. How do I make my toy appear. It uses the same network as my pc.

My iphone wireless 5ghz.
pc: LAN

I would appreciate the help

**Comment by Er1807** [comment]
From what I have seen is that it only works on the local device. After one update of lovense I was unable to connect it from my PC to my phone. Instead I used the PC version. Maybe it works if you open the website on the phone too

**Comment by M1zuke** [comment]
Sadly. This doesn't fix the issue. Opened the website in the phone but it still didn't show any toys :(

**Comment by markviews** [comment]
That's strange you would get an empty list of toys.. I'll look into this when I get home.

For now make sure your using the Lovense Connect app (the pink one NOT the blue one) also make sure your toy is toggled on in the app so part of the toggle thing turns green.

**Comment by M1zuke** [comment]
> For now make sure your using the Lovense Connect app (the pink one NOT the blue one) also make sure your toy is toggled on in the app so part of the toggle thing turns green.

I did exactly that. I followed every step in your instruction of the README.dm file but sadly my toy is not being found.

I have the suspicioun that my iphone might block this somehow?
my Iphone uses the new iOS 15 if this helps somehow.

**Comment by markviews** [comment]
oops I didn't mean to close this issue, I just uploaded the webpage code to the github. I'm working on fixing it rn.

**Comment by markviews** [comment]
hmm, i gotta update my dns I think. i'll try that when I get home

**Comment by markviews** [comment]
strange.. i'm not getting this error.
The webpage is hosted in 2 places, maybe try both 🤷 
[https://remote.markstuff.net/](https://remote.markstuff.net/)
[https://control.markstuff.net/](https://control.markstuff.net/)

**Comment by markviews** [comment]
ok I changed the connection to the lovense app to http so certificates don't matter because they seem to cause problems.

I'll make my server and webpage http soon so we don't have to deal with https certificate issues in the future.

For how you'll have to allow "Insecure content" on the webpage because it uses http and https
[https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html](https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html)

**Comment by rekcity** [comment]
trying to allow insecure content still did not work, and gave the same results. however when I downloaded the web page, it works fine.

**Comment by M1zuke** [comment]
I can confirm when downloading the webpage and starting it locally it does work :3
