### ISSUE TITLE
Likely Wont Last Long

### ISSUE THREAD

**Issue by OFWModz** [markviews/VRChatVibratorController#5]
This breaks Lovense's Terms and also uses their Trademark, this will likely get taken down by them soon.

I would know, I'm partnered with Lovense and had to change the name of my tool & stop using control links entirely.

**Comment by markviews** [comment]
Thanks for the heads up

**Comment by OFWModz** [comment]
Contact me on discord via http://krewella.co.uk/RealFeel and I can help out, as not only is the community/partnership manager for lovense there, i am too; being a partner.

Also, something like this does exist, just instead native esk support.
