### ISSUE TITLE
Can folove brand be controlled 

### ISSUE THREAD

**Issue by SmartArduino** [markviews/VRChatVibratorController#7]
https://www.folove.shop/products/loveai-wearable-vibrator-redesigned-powerful-quiet-stimulator-improved-long-distance-bluetooth-remote-reach-with-music-sync-partner-app-control
I think the appearance of this product is almost the same. Can I use your app

**Comment by markviews** [comment]
I'm guessing not, sorry. But if you can get it to connect to the official Lovense Connect app on your phone than it can be controlled using this mod.
