### ISSUE TITLE
emmVRC is not showing up in userdata

### ISSUE THREAD

**Issue by AriMaso** [markviews/VRChatVibratorController#8]
I downloaded melonloader and downloaded vibrator.controller.dll moved that to mods in VRchat mods but it's not working proper and shows i am disconnect from the server for the mod webpage to get a code for my toy... plis help

**Comment by markviews** [comment]
emmvrc data is not in modprefs.ini.
I recommend you ask for help in the emmvrc discord server.
https://discord.gg/emmvrc

**Comment by markviews** [comment]
Ohh sorry I see my server Is down sorry about that. I got confused because you mentioned emmvrc.
The server is back up now.
