### ISSUE TITLE
Buttons do not clear when the back button is not pressed

### ISSUE THREAD

**Issue by forever-and-a-day** [markviews/VRChatVibratorController#9]
the buttons for this mod are still visible when the menu is closed by pressing the quick menu button, behind the default buttons. see picture: https://files.catbox.moe/q0j8fi.jpg

**Comment by markviews** [comment]
I re-build the project and uploaded it, re-download version 1.2.5 for the fix. thanks for pointing this out to me.
[https://github.com/markviews/VRChatVibratorController/releases/tag/1.2.5](https://github.com/markviews/VRChatVibratorController/releases/tag/1.2.5)
